site_name: VHC-TestDataScience-1

nav:
  - Home: index.md
  - Data Cleaning: data-cleaning.md
  - Data Exploration: data-exploration.md
  - Feature Engineering: feature-engineering.md
  - Pre-processing: pre-processing.md
  - Modeling: modeling.md
  - XGBoost: xgboost.md
  - Results: results.md